<?php
/**
 * Created by PhpStorm.
 * User: drupalviking
 * Date: 06/05/15
 * Time: 08:47
 */
?>
<div class="layout layout--three-columns page-user-list">
	<section class="layout__section">
		<h1 class="layout__headline">Notendur (<?=count($this->users)?>)</h1>

<table class="block-table block-table--air">
  <thead>
  <tr>
    <td>Nafn</td>
    <td>Tölvupóstfang</td>
    <td>Dags.</td>
  </tr>
  </thead>
  <tbody>
  <?php foreach( $this->users as $user ) : ?>
    <tr>
      <td><?=($user->name)?$user->name:'&nbsp;'?></td>
      <td><?=($user->email)?$user->email:'&nbsp;'?></td>
      <td class="block-table__date"><time datetime="<?=strftime('%d. %B %Y', $user->created_date); ?>" class="block-item__time"><?=strftime('%d. %B %Y', $user->created_date); ?></time></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
</section>
</div>