<?php
/**
 * Created by PhpStorm.
 * User: drupalviking
 * Date: 06/05/15
 * Time: 11:49
 */
?>
<style>
  #map-canvas {
    width: 800px;
    height: 400px;
  }
</style>
<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
  function initialize() {
    var mapCanvas = document.getElementById('map-canvas');
    var mapOptions = {
      center: new google.maps.LatLng(<?=$airport->latitude;?>, <?=$airport->longitude;?>),
      zoom: 14,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(mapCanvas, mapOptions)
  }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>
<h1><?=$airport->name;?> (<?=$airport->airport_code; ?>)</h1>
<div id="map-canvas"></div>
<p><a href="<?=$this->url('airport/update',array('id'=>$this->airport->id));?>" class="update">Uppfæra upplýsingar</a></p>
<p><a href="<?=$this->url('airport');?>">Til baka í lista</a></p>


