<?php
/**
 * Created by PhpStorm.
 * User: drupalviking
 * Date: 06/05/15
 * Time: 10:12
 */
?>
<?php if( !$this->form ):?>

<?php else:?>
  <?php $this->form->setAttribute('class','form-horizontal'); ?>

  <div class="layout layout--three-columns page-login">
    <section class="layout__section">
      <div class="layout__meta page-login__manual">
        <p>Að sjálfsögðu er hægt að skrá sig inn með gamla mátanum</p>
        <?=$this->form()->openTag($this->form);?>

        <div class="form-group">
          <?=$this->formLabel($this->form->get('email'));?>
          <?=$this->formElement($this->form->get('email')->setAttribute('class','form-control'));?>
          <?=$this->formElementErrors($this->form->get('email'));?>
        </div>
        <div class="form-group">
          <?=$this->formLabel($this->form->get('passwd'));?>
          <?=$this->formElement($this->form->get('passwd')->setAttribute('class','form-control'));?>
          <?=$this->formElementErrors($this->form->get('passwd'));?>
        </div>

        <div class="form-group">
          <?=$this->formElement($this->form->get('submit')->setAttribute('class','btn btn-default'));?>
        </div>

        <?= $this->form()->closeTag() ?>


      </div>

    </section>
    <aside class="layout__aside"></aside>
  </div>
<?php endif;?>